# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_msg', models.CharField(max_length=32, verbose_name='携带token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='app.UserInfo')),
            ],
        ),
    ]
